project:
  type: website
  output-dir: _site

website:
  title: "Blog Personal"
  description: "Un espacio para aprender sobre física."
  navbar:
    left:
      - href: fisica.qmd
        text: Física
      - href: ensayos.qmd
        text: Ensayos
      - href: about.qmd
        text: Sobre mí
    right:
      - icon: github
        href: https://github.com/Diego5717/mi-blog
      - icon: instagram
        href: https://instagram.com/TU_USUARIO

format:
  html:
    theme: merlot      # cambia por: darkly, flatly, solar, etc.
    css: styles.css
    toc: true             # tabla de contenidos automática
    code-fold: true       # el código aparece plegado (clic para ver)
    code-tools: true

# Ejecuta el código Python al renderizar
execute:
  freeze: auto            # solo re-ejecuta si cambia el código (ahorra tiempo)
