---
title: "Física"
toc: false
---

Dividido por las áreas de la física, aqui se pueden ver los pequeños estudios de los fenomenos físicos que he hecho e iré haciendo. 

## Mecánica {#mecanica}

::: {.grid}

::: {.g-col-12 .g-col-md-6}
::: {.sim-card}
### Dinámica de un fluido con diferencia de temperatura.

[Mecánica]{.tag} [Fluidos]{.tag} [Medios Deformables]{.tag}

Como es la dinámica de un fluido cuando se le tiene encerrado en una caja bidimensional con diferencia de temperatura en sus paredes lateriales y la tapa superior e inferior son paredes adiabaticas.

[Ver →](posts/mecanica/conveccion_frio_calor/index.qmd){.btn-ver}
:::
:::

:::

## Termodinámica {#termodinamica}

::: {.pronto}
Próximamente.
:::

## Física estadística {#estadistica}

::: {.grid}

::: {.g-col-12 .g-col-md-6}
::: {.sim-card}
### Estudio de una multitud por medio de una aproximación de fluidos.

[Física Estadística]{.tag} [Fluidos]{.tag}

El estudio del comportamiento de las casi 900 mil personas que asistieron a la vez al monumento de la independencia para celebrar la victoria de México sobre ecuador en el mundial del 2026.

[Ver →](posts/estadistica/monumento_indep/index.qmd){.btn-ver}
:::
:::

:::

## Cuántica {#cuantica}

::: {.pronto}
Próximamente.
:::

## Relatividad {#relatividad}

::: {.pronto}
Próximamente.
:::
